---
# tasks/main.yml (ffmpeg)
# Prefix : ffmpeg

- name: Pre-check variables
  import_tasks: pre_check.yml
  tags: ["pre_check"]

- name: Install tasks
  import_tasks: install.yml
  when:
    - ffmpeg_install_flag | bool
  tags: ["install"]